### list hosts
GET http://localhost:3000/hosts

### get a host
GET http://localhost:3000/hosts/1

### create a host
POST http://localhost:3000/hosts
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.9"
}

### update a host
PUT http://localhost:3000/hosts/2242
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### delete a host
DELETE http://localhost:3000/hosts/2242
