@domain=http://localhost:3000

### list hosts
GET {{domain}}/hosts

### get a host
GET {{domain}}/hosts/1

### create a host
POST {{domain}}/hosts
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.9"
}

### update a host
PUT {{domain}}/hosts/2242
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### delete a host
DELETE {{domain}}/hosts/2242
