@server = http://localhost:3000

### hello/en

GET {{server}}/hello/en?name=Luiz

### hello/pt

GET {{server}}/hello/pt/Luiz

### hello/es

POST {{server}}/hello/es
Content-Type: application/json

{
  "name": "Luiz"
}
